//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_projectPriva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email_add { get; set; }
        public string Username { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    }
}
