//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_projectPriva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Insurance_Customer = new HashSet<Insurance_Customer>();
        }
    
        public int Id { get; set; }
        public string Car_Model { get; set; }
        public string Car_Brand { get; set; }
        public string Car_No { get; set; }
        public string Register_Date { get; set; }
        public string Owner_Name { get; set; }
        public string Car_Type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Insurance_Customer> Insurance_Customer { get; set; }
    }
}
